### ISSUE TITLE
Rut con dígito validador 0.

### ISSUE THREAD

**Issue by vilaboa** [vichoconejeros/react-rut#1]
He probado con varios rut terminados en 0 y la respuesta es **false**.
ej: 12458266-0

**Comment by vicenteconejerosdelacruz** [comment]
gracias por el rut ejemplo, le voy a hechar una mirada a ver donde quedo mal hecho el calculo

**Comment by vicenteconejerosdelacruz** [comment]
ok, creo que esto se arregla cambiando la linea 26, el '11' por '0'(lo probe y me funciono, el 11 no tiene sentido). si no te rompe nada(otros ruts) lo subo y lo damos por resuelto
Saludos y de pasada gracias por usar esto, trate de que fuera facil de integrar

**Comment by vicenteconejerosdelacruz** [comment]
parche aplicado

**Comment by vilaboa** [comment]
Super! Es lo mismo que probé yo.
Así que debe funcionar. Gracias a ti.

Saludos!
